apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/rancher/k3s/k3s.yaml
leaderElection:
  leaderElect: false
profiles:
- schedulerName: my-gpu-scheduler
  plugins:
    queueSort:
      enabled:
      - name: "PrioritySort"
    preFilter:
      disabled:
      - name: "DefaultPreemption"
      enabled:
      - name: "GangScheduling"
    permit:
      enabled:
      - name: "GangScheduling"
    postFilter:
      enabled:
      - name: "GangScheduling"
    reserve:
      enabled:
      - name: "GangScheduling"
